/* eslint-disable import/prefer-default-export */

export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_ERROR = 'GET_ALL_CATEGORIES_ERROR';
export const CREATE_CATEGORIES_SUCCESS = 'CREATE_CATEGORIES_SUCCESS';
export const CREATE_CATEGORIES_ERROR = 'CREATE_CATEGORIES_ERROR';
export const UPDATE_CATEGORIES_SUCCESS = 'UPDATE_CATEGORIES_SUCCESS';
export const UPDATE_CATEGORIES_ERROR = 'UPDATE_CATEGORIES_ERROR';
export const DESTROY_CATEGORIES_SUCCESS = 'DESTROY_CATEGORIES_SUCCESS';
export const DESTROY_CATEGORIES_ERROR = 'DESTROY_CATEGORIES_ERROR';

export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';
export const DESTROY_TODO_SUCCESS = 'DESTROY_TODO_SUCCESS';
export const DESTROY_TODO_ERROR = 'DESTROY_TODO_ERROR';
