# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c63033ffb755a10e4c0bb6ebe80a95e8ad8dbfed8735a7569c91f3dab0727b760902606616d3301c79d09ab89e39f9d8df27f19fd5e39ebd55507acd47d9b212

test:
  secret_key_base: 9cc8c941369d43617acafab3d28eb2f8123c9f80dd010761c34f9822abc830356ef8246e8d000b698bdd6bd4eefa389ab64509a73c4a696094a02d0ffe827244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
